---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-manager-crb
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: crd-manager
  apiGroup: rbac.authorization.k8s.io
