apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-metrics
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: homework
roleRef:
  kind: ClusterRole
  name: metrics-clusterrole
  apiGroup: rbac.authorization.k8s.io
