apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "template-chart-test-app.fullname" . }}-ingress
  labels:
    {{- include "template-chart-test-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  rules:
  - host: "homework.otus"
    http:
      paths:
      - path: /homepage()(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "template-chart-test-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      - path: /(conf)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "template-chart-test-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      - path: /(metrics)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "template-chart-test-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}
