apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "template-chart-test-app.labels" . | nindent 4 }}
  name: {{ include "template-chart-test-app.fullname" . }}
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
  type: {{ .Values.service.type }}
