apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: proxy
  name: {{ include "template-chart-test-app.fullname" . }}
  namespace: homework
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
  type: {{ .Values.service.type }}
