{{- if .Values.pvc.create -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.pvc.storageClassName }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain # default value is Delete
mountOptions:
  - discard # this might enable UNMAP / TRIM at the block storage layer
volumeBindingMode: Immediate
{{- end }}
