all:
  vars:
    ansible_ssh_user: yc-user
  hosts:
    node1:
      ansible_host: 89.169.139.104
      ip: 10.128.0.10
    node2:
      ansible_host: 89.169.137.18
      ip: 10.128.0.22
    node3:
      ansible_host: 89.169.141.87
      ip: 10.128.0.34
    node4:
      ansible_host: 89.169.135.65
      ip: 10.128.0.30
    node5:
      ansible_host: 89.169.134.176
      ip: 10.128.0.32
  children:
    kube_control_plane:
      hosts:
        node1:
        node4:
        node5:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node4:
        node5:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
