apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi
  storageClassName: ""
  selector:
    matchLabels:
      release: "test"

