apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi

